name: Your New Jekyll Site
description: Blogging about stuffs
meta_description: "dev garden, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: /
domain_name: 'http://darek.io'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://darek.io'
author:         'Darek Zoń'
