name: dev garden
description: when technology meets nature
meta_description: "dev garden, when technology meets nature"

markdown: kramdown
highlighter: rouge
logo: /assets/images/profile.jpg

paginate: 10
baseurl: /
domain_name: 'http://darek.io'
google_analytics: 'UA-158924715-1'
plugins:
  - jekyll-paginate
  - jekyll-gist

# Details for the RSS feed generator
url:            'http://darek.io'
author:         'Darek Zoń'
